on: push

jobs:
    build:
        runs-on: ubuntu-latest
        container: registry.gitlab.com/islandoftex/images/texlive:latest
        steps:
            - run: arara -lv Komunikacijska\ vezja\ in\ naprave.tex
            
            - name: Upload math result for job 1
              uses: actions/upload-artifact@v3.1.1
              with:
                  name: homework
                  path: ./*.pdf
